# Numpy Basic

In [1]:
import numpy as np

In [35]:
print(np.__version__)

1.21.6


In [36]:
a = [10,20,30,45,23,67,34]
print(type(a))

<class 'list'>


In [37]:
b = np.array(a)
print(type(b)) #ndarray -> n dimentional array

<class 'numpy.ndarray'>


In [38]:
print(b)
print(a)

[10 20 30 45 23 67 34]
[10, 20, 30, 45, 23, 67, 34]


[10 20 30 45 23 67 34] -> 1-d Array
[[10 20 30] [40 50 60]] -> 2-d Array
[[[1 2] [3 4]] [[5 7] [6 8]]] -> 3-d Array (image processing) n-d Array

In [39]:
print(b.ndim)

1


In [40]:
d2arr = np.array([[10,20,30],[40,50,60]])
print(d2arr.ndim)
print(type(d2arr))
print(d2arr)

2
<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]


In [44]:
arr = np.array([10,20,30,45,23,67,34], ndmin=5)
print(arr.ndim)
print(arr)

5
[[[[[10 20 30 45 23 67 34]]]]]


In [54]:
a = np.array([20,43,65,78,90,12,342,65])
print(a)

[ 20  43  65  78  90  12 342  65]


In [48]:
#accessing ndarray elements using indexing
print(a[2])
print(a[-2])

65
342


In [49]:
a2 = np.array([[20,43],[65,78],[90,12],[342,65]])
print(a2)

[[ 20  43]
 [ 65  78]
 [ 90  12]
 [342  65]]


In [52]:
print(a2[3,0])

342


In [56]:
#accessing ndarray elements using slicing
print(a[1:4])

[43 65 78]


In [57]:
print(a2[1:3,:])

[[65 78]
 [90 12]]


In [58]:
print(a2.dtype)

int32


In [60]:
print(a.dtype)

int32


In [61]:
ab = np.array([1.0,9.4,8.6])
print(ab.dtype)

float64


In [62]:
abc = np.array(["hello","world","of",'python'])
print(abc.dtype)

<U6


In [65]:
abcd = np.array([1,2,3,4], dtype='U')
print(abcd.dtype)

<U1


In [66]:
print(abcd)

['1' '2' '3' '4']


In [68]:
abcd = np.array([1,2,3,4], dtype='i8')
print(abcd.dtype)

int64


In [70]:
xyz = np.array([1,2,3,4])
print(xyz.dtype)

int32


In [71]:
xyz1 = xyz.astype('S')
print(xyz1.dtype)

|S11


In [73]:
print(xyz1)

[b'1' b'2' b'3' b'4']


In [75]:

a = np.array([1,2,3])
b = a.copy()
print(a,b)
a[0] = 100
print(a,b)

[1 2 3] [1 2 3]
[100   2   3] [1 2 3]


In [76]:
a = np.array([1,2,3,4])
print(a.ndim)
print(a.shape)

1
(4,)


In [77]:
a = np.array([[1,2],[3,4],[10,90]])
print(a.ndim)
print(a.shape)

2
(3, 2)


In [81]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.shape)
print(a.ndim)

(10,)
1


In [82]:
b = a.reshape(5,2)
print(b.ndim)
print(b.shape)

2
(5, 2)


In [83]:
print(b)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [84]:
c = b.reshape(-1) #flattening
print(c.ndim)
print(c.shape)

1
(10,)


In [85]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
a = np.array([1,2,3,4,5,6])
for i in a:
    print(i)

1
2
3
4
5
6


In [4]:
b = np.array([[1,2],[3,4],[5,6]])
for i in b:
    for j in i:
        print(j)

1
2
3
4
5
6


In [5]:
marks = np.array([78,98,56,73,56,90])
age = np.array([23,22,25,21,19,24])
#concatenate() -> 1st arg (tuple of arrays), 2nd arg (axis=0,1 (0 is default)), returns a merged array
res = np.concatenate((marks,age))
print(res)

[78 98 56 73 56 90 23 22 25 21 19 24]


In [6]:
res = np.concatenate((marks,age), axis=1)
print(res)

AxisError: axis 1 is out of bounds for array of dimension 1

In [11]:
marks = np.array([[78,98],[56,73],[56,90]])
age = np.array([[23,22],[25,21],[19,24]])
res = np.concatenate((marks,age), axis=1)
print(res)

[[78 98 23 22]
 [56 73 25 21]
 [56 90 19 24]]


In [12]:
res = np.concatenate((marks,age))
print(res)

[[78 98]
 [56 73]
 [56 90]
 [23 22]
 [25 21]
 [19 24]]


In [16]:
marks = np.array([78,98,56,73,56,90])
age = np.array([23,22,25,21,19,24])
#stack() -> 1st arg (tuple of arrays), 2nd arg (axis=0,1 (0 is default)), returns a stacked array
res = np.stack((marks,age))
print(res)
print(res.ndim)

[[78 98 56 73 56 90]
 [23 22 25 21 19 24]]
2


In [17]:
marks = np.array([78,98,56,73,56,90])
age = np.array([23,22,25,21,19,24])
#stack() -> 1st arg (tuple of arrays), 2nd arg (axis=0,1 (0 is default)), returns a stacked array
res = np.stack((marks,age), axis=1)
print(res)
print(res.ndim)

[[78 23]
 [98 22]
 [56 25]
 [73 21]
 [56 19]
 [90 24]]
2


In [21]:
marks = np.array([[78,98],[56,73],[56,90]])
age = np.array([[23,22],[25,21],[19,24]])
res = np.stack((marks,age), axis = 1)
print(res)
print(res.ndim)

[[[78 98]
  [23 22]]

 [[56 73]
  [25 21]]

 [[56 90]
  [19 24]]]
3


In [25]:
a3d = np.array([[[78],[98]],[[56],[73]],[[56],[90]]])
b3d = np.array([[[23],[22]],[[25],[21]],[[19],[24]]])
res = np.dstack((a3d,b3d))
print(a3d)
print(res)

[[[78]
  [98]]

 [[56]
  [73]]

 [[56]
  [90]]]
[[[78 23]
  [98 22]]

 [[56 25]
  [73 21]]

 [[56 19]
  [90 24]]]


In [26]:
res = np.vstack((a3d,b3d))
print(res)

[[[78]
  [98]]

 [[56]
  [73]]

 [[56]
  [90]]

 [[23]
  [22]]

 [[25]
  [21]]

 [[19]
  [24]]]


In [36]:
marks = np.array([78,98,56,73,56,34])
# array_split(arr, nos) -> arr (array to split), nos (number of split)
res = np.array_split(marks, 3)
print(res)

[array([78, 98]), array([56, 73]), array([56, 34])]


In [41]:
marks = np.array([78,98,56,73,56])
res = np.array_split(marks, 3)
print(res)

[array([78, 98]), array([56, 73]), array([56])]


In [44]:
marks = np.array([[78,98],[56,73],[56,90]])
res = np.array_split(marks, 4)
print(res)

[array([[78, 98]]), array([[56, 73]]), array([[56, 90]]), array([], shape=(0, 2), dtype=int32)]


In [53]:
marks = np.array([78,98,56,73,56,34,89,54,78])
res = np.where(marks>=60)
print(res)

(array([0, 1, 3, 6, 8], dtype=int64),)


In [52]:
# create a list of size of array
# this list must contain only boolean values (True, False)
# put True at those indexes where you want the output
x = [True, True, False, True, False]
res = marks[x]
print(res)

[78 98 73]


In [56]:
x = []
for i in marks:
    if i >= 30 and i<60:
        x.append(True)
    else:
        x.append(False)
res = marks[x]
print(res)

[56 56 34 54]


In [55]:
res = marks[marks>=60]
print(res)

[78 98 73 89 78]


In [51]:
res = np.sort(marks)
print(res)

[56 56 73 78 98]


In [57]:
res = np.sum(marks)
print(res)

616
