In [5]:
import numpy as np

In [2]:
a = np.array([1,2,3,4],ndmin=2)
a

array([[1, 2, 3, 4]])

In [3]:
b = np.array([1,2,3,4,5,6,7,8])
print(b)

[1 2 3 4 5 6 7 8]


In [6]:
c = b[3:7]
print(c)

[4 5 6 7]


In [9]:
d = np.array([[1,2,3,4,-1]])
e = d.reshape(-1)
print(e)

[ 1  2  3  4 -1]


In [12]:
for i in d:
    for j in i:
        print(j)

1
2
3
4
-1


In [13]:
ab = np.array([1,2,3,4,5])
ba = np.array([5,6,7,8,9])
ca = np.concatenate((ab,ba)) #Horizontal concatenate,axis=0 by default
print(ca)

[1 2 3 4 5 5 6 7 8 9]


In [15]:
ab = np.array([1,2,3,4,5],ndmin=2)
ba = np.array([5,6,7,8,9],ndmin=2)
ca = np.concatenate((ab,ba),axis=1)
print(ca)

[[1 2 3 4 5 5 6 7 8 9]]


In [20]:
ab = np.array([[1,2],[3,4],[5,6]])
ba = np.array([[5,6],[7,8],[9,10]])
ca = np.concatenate((ab,ba),axis=1) #Vertical concatenate,axis=1)
print(ca)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 5  6  9 10]]


In [17]:
ab = np.array([1,2,3,4,5])
ba = np.array([5,6,7,8,9])
ca = np.stack((ab,ba)) # Horizontal stacking,axis=0 by default
print(ca)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [21]:
ab = np.array([1,2,3,4,5])
ba = np.array([5,6,7,8,9])
ca = np.stack((ab,ba),axis=1) #vertical stacking,axis = 1 
print(ca)

[[1 5]
 [2 6]
 [3 7]
 [4 8]
 [5 9]]


In [31]:
ab = np.array([1,2,3,4,5])
ba = np.array([5,6,7,8,9])
cb= np.array([10,20,30,40,50])
ca = np.stack((ab,ba,cb),axis=1) #vertical stacking,axis = 1 
print(ca)

[[ 1  5 10]
 [ 2  6 20]
 [ 3  7 30]
 [ 4  8 40]
 [ 5  9 50]]


In [32]:
ab = np.array([[1,2],[3,4],[5,6]])
ba = np.array([[5,6],[7,8],[9,10]])
ca = np.stack((ab,ba),axis=1)
print(ca)

[[[ 1  2]
  [ 5  6]]

 [[ 3  4]
  [ 7  8]]

 [[ 5  6]
  [ 9 10]]]


In [33]:
ab = np.array([[1,2],[3,4],[5,6]])
ba = np.array([[5,6],[7,8],[9,10]])
ca = np.stack((ab,ba))
print(ca)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]]


In [35]:
ab = np.array([[1,2],[3,4],[5,6]])
ba = np.array([[5,6],[7,8],[9,10]])
ca = np.stack((ab,ba),axis=1)
print(ca)

[[[ 1  2]
  [ 5  6]]

 [[ 3  4]
  [ 7  8]]

 [[ 5  6]
  [ 9 10]]]


In [38]:
ab = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
ba = np.array([[[5],[6]],[[7],[8]],[[9],[10]]])
ca = np.stack((ab,ba))
print(ca)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 5]
   [ 6]]

  [[ 7]
   [ 8]]

  [[ 9]
   [10]]]]


In [41]:
ab = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
ba = np.array([[[5],[6]],[[7],[8]],[[9],[10]]])
ca = np.dstack((ab,ba))
print(ca)

[[[ 1  5]
  [ 2  6]]

 [[ 3  7]
  [ 4  8]]

 [[ 5  9]
  [ 6 10]]]


In [42]:
ab = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
ba = np.array([[[5],[6]],[[7],[8]],[[9],[10]]])
ca = np.hstack((ab,ba))
print(ca)


[[[ 1]
  [ 2]
  [ 5]
  [ 6]]

 [[ 3]
  [ 4]
  [ 7]
  [ 8]]

 [[ 5]
  [ 6]
  [ 9]
  [10]]]


In [43]:
ab = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
ba = np.array([[[5],[6]],[[7],[8]],[[9],[10]]])
ca = np.vstack((ab,ba))
print(ca)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]]


In [44]:
ab = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
ba = np.array([[[5],[6]],[[7],[8]],[[9],[10]]])
ca = np.stack((ab,ba),axis=0)
print(ca)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 5]
   [ 6]]

  [[ 7]
   [ 8]]

  [[ 9]
   [10]]]]


In [48]:
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,6) # array_split(variable,split_no.)
print(b)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [49]:
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,4) # array_split(variable,split_no.)
print(b)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [52]:
ab = np.array([[1,2],[3,4],[5,6]])
ba = np.array([[5,6],[7,8],[9,10]])
cx = np.array_split(ab,4)
print(cx,"\n")
dx = np.array_split(ba,3)
print(dx,"\n")
zc = np.array_split(ba,2)
print(zc,"\n")

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([], shape=(0, 2), dtype=int32)] 

[array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]])] 

[array([[5, 6],
       [7, 8]]), array([[ 9, 10]])] 



In [53]:
a = np.array([1,2,3,4,5,3,6])
b = np.where(a>3)
print(b)


(array([3, 4, 6], dtype=int64),)


In [54]:
a = np.array([1,2,3,4,5,3,6])
b = np.sort(a)
b

array([1, 2, 3, 3, 4, 5, 6])

In [59]:
a = np.array([1,2,3,4,5,3,6])
b = [True,False,True,True,False,True,True]
res = a[b]
print(res)
# This is a static approach

[1 3 4 3 6]


In [62]:
x = []
for i in a:
    if i>3:
        x.append(True)
    else:
        x.append(False)
res = a[x]
print(res)
# Now this is dynamic approach
 

[4 5 6]


In [64]:
res = a[a>3]
print(res)
# This is a shortcut for small conditions

[4 5 6]


In [82]:
v = np.array([1,2,3,4,5])
ast = 0
for i in range(len(v)):
    ast += v[i]
print(ast)

15


In [4]:
# Question 1
import numpy as np
a = np.array([-1,-2,3,4,5])
a[a<0]=0
print(a)

[0 0 3 4 5]


In [7]:
a = np.array([10,20,30])
b = np.array([40,50,60])
c = np.stack((a,b),axis=1)
print(c)

[[10 40]
 [20 50]
 [30 60]]
